//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimCurrency")]
	public partial class Currency : XPLiteObject
	{
		int fCurrencyKey;
		[Key(true)]
		public int CurrencyKey
		{
			get
			{
				return fCurrencyKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(CurrencyKey), ref fCurrencyKey, value);
			}
		}
		string fCurrencyLabel;
		[Indexed(Name = @"AK_DimCurrency_CurrencyLabel", Unique = true)]
		[Size(10)]
		public string CurrencyLabel
		{
			get
			{
				return fCurrencyLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(CurrencyLabel), ref fCurrencyLabel, value);
			}
		}
		string fCurrencyName;
		[Size(20)]
		public string CurrencyName
		{
			get
			{
				return fCurrencyName;
			}
			set
			{
				SetPropertyValue<string>(nameof(CurrencyName), ref fCurrencyName, value);
			}
		}
		string fCurrencyDescription;
		[Size(50)]
		public string CurrencyDescription
		{
			get
			{
				return fCurrencyDescription;
			}
			set
			{
				SetPropertyValue<string>(nameof(CurrencyDescription), ref fCurrencyDescription, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
		[Association(@"FactExchangeRateReferencesCurrency")]
		public XPCollection<FactExchangeRate> FactExchangeRates
		{
			get
			{
				return GetCollection<FactExchangeRate>(nameof(FactExchangeRates));
			}
		}
		[Association(@"FactInventoryReferencesCurrency")]
		public XPCollection<FactInventory> FactInventories
		{
			get
			{
				return GetCollection<FactInventory>(nameof(FactInventories));
			}
		}
		[Association(@"FactOnlineSalesReferencesCurrency")]
		public XPCollection<FactOnlineSales> FactOnlineSalesCollection
		{
			get
			{
				return GetCollection<FactOnlineSales>(nameof(FactOnlineSalesCollection));
			}
		}
		[Association(@"FactSalesReferencesCurrency")]
		public XPCollection<Sales> FactSalesCollection
		{
			get
			{
				return GetCollection<Sales>(nameof(FactSalesCollection));
			}
		}
		[Association(@"FactSalesQuotaReferencesCurrency")]
		public XPCollection<FactSalesQuota> FactSalesQuotas
		{
			get
			{
				return GetCollection<FactSalesQuota>(nameof(FactSalesQuotas));
			}
		}
		[Association(@"FactStrategyPlanReferencesCurrency")]
		public XPCollection<FactStrategyPlan> FactStrategyPlans
		{
			get
			{
				return GetCollection<FactStrategyPlan>(nameof(FactStrategyPlans));
			}
		}
	}

}
