//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimCustomer")]
	public partial class Customer : XPLiteObject
	{
		int fCustomerKey;
		[Key(true)]
		public int CustomerKey
		{
			get
			{
				return fCustomerKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(CustomerKey), ref fCustomerKey, value);
			}
		}
		Geography fGeographyKey;
		[Association(@"CustomerReferencesGeography")]
		public Geography GeographyKey
		{
			get
			{
				return fGeographyKey;
			}
			set
			{
				SetPropertyValue<Geography>(nameof(GeographyKey), ref fGeographyKey, value);
			}
		}
		string fCustomerLabel;
		[Indexed(Name = @"IX_DimCustomer_CustomerLabel", Unique = true)]
		public string CustomerLabel
		{
			get
			{
				return fCustomerLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(CustomerLabel), ref fCustomerLabel, value);
			}
		}
		string fTitle;
		[Size(8)]
		public string Title
		{
			get
			{
				return fTitle;
			}
			set
			{
				SetPropertyValue<string>(nameof(Title), ref fTitle, value);
			}
		}
		string fFirstName;
		[Size(50)]
		public string FirstName
		{
			get
			{
				return fFirstName;
			}
			set
			{
				SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value);
			}
		}
		string fMiddleName;
		[Size(50)]
		public string MiddleName
		{
			get
			{
				return fMiddleName;
			}
			set
			{
				SetPropertyValue<string>(nameof(MiddleName), ref fMiddleName, value);
			}
		}
		string fLastName;
		[Size(50)]
		public string LastName
		{
			get
			{
				return fLastName;
			}
			set
			{
				SetPropertyValue<string>(nameof(LastName), ref fLastName, value);
			}
		}
		bool fNameStyle;
		public bool NameStyle
		{
			get
			{
				return fNameStyle;
			}
			set
			{
				SetPropertyValue<bool>(nameof(NameStyle), ref fNameStyle, value);
			}
		}
		DateTime fBirthDate;
		public DateTime BirthDate
		{
			get
			{
				return fBirthDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(BirthDate), ref fBirthDate, value);
			}
		}
		char fMaritalStatus;
		public char MaritalStatus
		{
			get
			{
				return fMaritalStatus;
			}
			set
			{
				SetPropertyValue<char>(nameof(MaritalStatus), ref fMaritalStatus, value);
			}
		}
		string fSuffix;
		[Size(10)]
		public string Suffix
		{
			get
			{
				return fSuffix;
			}
			set
			{
				SetPropertyValue<string>(nameof(Suffix), ref fSuffix, value);
			}
		}
		string fGender;
		[Size(1)]
		public string Gender
		{
			get
			{
				return fGender;
			}
			set
			{
				SetPropertyValue<string>(nameof(Gender), ref fGender, value);
			}
		}
		string fEmailAddress;
		[Size(50)]
		public string EmailAddress
		{
			get
			{
				return fEmailAddress;
			}
			set
			{
				SetPropertyValue<string>(nameof(EmailAddress), ref fEmailAddress, value);
			}
		}
		decimal fYearlyIncome;
		public decimal YearlyIncome
		{
			get
			{
				return fYearlyIncome;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(YearlyIncome), ref fYearlyIncome, value);
			}
		}
		byte fTotalChildren;
		public byte TotalChildren
		{
			get
			{
				return fTotalChildren;
			}
			set
			{
				SetPropertyValue<byte>(nameof(TotalChildren), ref fTotalChildren, value);
			}
		}
		byte fNumberChildrenAtHome;
		public byte NumberChildrenAtHome
		{
			get
			{
				return fNumberChildrenAtHome;
			}
			set
			{
				SetPropertyValue<byte>(nameof(NumberChildrenAtHome), ref fNumberChildrenAtHome, value);
			}
		}
		string fEducation;
		[Size(40)]
		public string Education
		{
			get
			{
				return fEducation;
			}
			set
			{
				SetPropertyValue<string>(nameof(Education), ref fEducation, value);
			}
		}
		string fOccupation;
		public string Occupation
		{
			get
			{
				return fOccupation;
			}
			set
			{
				SetPropertyValue<string>(nameof(Occupation), ref fOccupation, value);
			}
		}
		char fHouseOwnerFlag;
		public char HouseOwnerFlag
		{
			get
			{
				return fHouseOwnerFlag;
			}
			set
			{
				SetPropertyValue<char>(nameof(HouseOwnerFlag), ref fHouseOwnerFlag, value);
			}
		}
		byte fNumberCarsOwned;
		public byte NumberCarsOwned
		{
			get
			{
				return fNumberCarsOwned;
			}
			set
			{
				SetPropertyValue<byte>(nameof(NumberCarsOwned), ref fNumberCarsOwned, value);
			}
		}
		string fAddressLine1;
		[Size(120)]
		public string AddressLine1
		{
			get
			{
				return fAddressLine1;
			}
			set
			{
				SetPropertyValue<string>(nameof(AddressLine1), ref fAddressLine1, value);
			}
		}
		string fAddressLine2;
		[Size(120)]
		public string AddressLine2
		{
			get
			{
				return fAddressLine2;
			}
			set
			{
				SetPropertyValue<string>(nameof(AddressLine2), ref fAddressLine2, value);
			}
		}
		string fPhone;
		[Size(20)]
		public string Phone
		{
			get
			{
				return fPhone;
			}
			set
			{
				SetPropertyValue<string>(nameof(Phone), ref fPhone, value);
			}
		}
		DateTime fDateFirstPurchase;
		public DateTime DateFirstPurchase
		{
			get
			{
				return fDateFirstPurchase;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(DateFirstPurchase), ref fDateFirstPurchase, value);
			}
		}
		string fCustomerType;
		[Size(15)]
		public string CustomerType
		{
			get
			{
				return fCustomerType;
			}
			set
			{
				SetPropertyValue<string>(nameof(CustomerType), ref fCustomerType, value);
			}
		}
		string fCompanyName;
		public string CompanyName
		{
			get
			{
				return fCompanyName;
			}
			set
			{
				SetPropertyValue<string>(nameof(CompanyName), ref fCompanyName, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
		[Association(@"FactOnlineSalesReferencesCustomer")]
		public XPCollection<OnlineSales> FactOnlineSalesCollection
		{
			get
			{
				return GetCollection<OnlineSales>(nameof(FactOnlineSalesCollection));
			}
		}
	}

}
