//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimDate")]
	public partial class Date : XPLiteObject
	{
		DateTime fDatekey;
		[Key]
		public DateTime Datekey
		{
			get
			{
				return fDatekey;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(Datekey), ref fDatekey, value);
			}
		}
		string fFullDateLabel;
		[Size(20)]
		public string FullDateLabel
		{
			get
			{
				return fFullDateLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(FullDateLabel), ref fFullDateLabel, value);
			}
		}
		string fDateDescription;
		[Size(20)]
		public string DateDescription
		{
			get
			{
				return fDateDescription;
			}
			set
			{
				SetPropertyValue<string>(nameof(DateDescription), ref fDateDescription, value);
			}
		}
		int fCalendarYear;
		public int CalendarYear
		{
			get
			{
				return fCalendarYear;
			}
			set
			{
				SetPropertyValue<int>(nameof(CalendarYear), ref fCalendarYear, value);
			}
		}
		string fCalendarYearLabel;
		[Size(20)]
		public string CalendarYearLabel
		{
			get
			{
				return fCalendarYearLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(CalendarYearLabel), ref fCalendarYearLabel, value);
			}
		}
		int fCalendarHalfYear;
		public int CalendarHalfYear
		{
			get
			{
				return fCalendarHalfYear;
			}
			set
			{
				SetPropertyValue<int>(nameof(CalendarHalfYear), ref fCalendarHalfYear, value);
			}
		}
		string fCalendarHalfYearLabel;
		[Size(20)]
		public string CalendarHalfYearLabel
		{
			get
			{
				return fCalendarHalfYearLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(CalendarHalfYearLabel), ref fCalendarHalfYearLabel, value);
			}
		}
		int fCalendarQuarter;
		public int CalendarQuarter
		{
			get
			{
				return fCalendarQuarter;
			}
			set
			{
				SetPropertyValue<int>(nameof(CalendarQuarter), ref fCalendarQuarter, value);
			}
		}
		string fCalendarQuarterLabel;
		[Size(20)]
		public string CalendarQuarterLabel
		{
			get
			{
				return fCalendarQuarterLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(CalendarQuarterLabel), ref fCalendarQuarterLabel, value);
			}
		}
		int fCalendarMonth;
		public int CalendarMonth
		{
			get
			{
				return fCalendarMonth;
			}
			set
			{
				SetPropertyValue<int>(nameof(CalendarMonth), ref fCalendarMonth, value);
			}
		}
		string fCalendarMonthLabel;
		[Size(20)]
		public string CalendarMonthLabel
		{
			get
			{
				return fCalendarMonthLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(CalendarMonthLabel), ref fCalendarMonthLabel, value);
			}
		}
		int fCalendarWeek;
		public int CalendarWeek
		{
			get
			{
				return fCalendarWeek;
			}
			set
			{
				SetPropertyValue<int>(nameof(CalendarWeek), ref fCalendarWeek, value);
			}
		}
		string fCalendarWeekLabel;
		[Size(20)]
		public string CalendarWeekLabel
		{
			get
			{
				return fCalendarWeekLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(CalendarWeekLabel), ref fCalendarWeekLabel, value);
			}
		}
		int fCalendarDayOfWeek;
		public int CalendarDayOfWeek
		{
			get
			{
				return fCalendarDayOfWeek;
			}
			set
			{
				SetPropertyValue<int>(nameof(CalendarDayOfWeek), ref fCalendarDayOfWeek, value);
			}
		}
		string fCalendarDayOfWeekLabel;
		[Size(10)]
		public string CalendarDayOfWeekLabel
		{
			get
			{
				return fCalendarDayOfWeekLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(CalendarDayOfWeekLabel), ref fCalendarDayOfWeekLabel, value);
			}
		}
		int fFiscalYear;
		public int FiscalYear
		{
			get
			{
				return fFiscalYear;
			}
			set
			{
				SetPropertyValue<int>(nameof(FiscalYear), ref fFiscalYear, value);
			}
		}
		string fFiscalYearLabel;
		[Size(20)]
		public string FiscalYearLabel
		{
			get
			{
				return fFiscalYearLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(FiscalYearLabel), ref fFiscalYearLabel, value);
			}
		}
		int fFiscalHalfYear;
		public int FiscalHalfYear
		{
			get
			{
				return fFiscalHalfYear;
			}
			set
			{
				SetPropertyValue<int>(nameof(FiscalHalfYear), ref fFiscalHalfYear, value);
			}
		}
		string fFiscalHalfYearLabel;
		[Size(20)]
		public string FiscalHalfYearLabel
		{
			get
			{
				return fFiscalHalfYearLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(FiscalHalfYearLabel), ref fFiscalHalfYearLabel, value);
			}
		}
		int fFiscalQuarter;
		public int FiscalQuarter
		{
			get
			{
				return fFiscalQuarter;
			}
			set
			{
				SetPropertyValue<int>(nameof(FiscalQuarter), ref fFiscalQuarter, value);
			}
		}
		string fFiscalQuarterLabel;
		[Size(20)]
		public string FiscalQuarterLabel
		{
			get
			{
				return fFiscalQuarterLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(FiscalQuarterLabel), ref fFiscalQuarterLabel, value);
			}
		}
		int fFiscalMonth;
		public int FiscalMonth
		{
			get
			{
				return fFiscalMonth;
			}
			set
			{
				SetPropertyValue<int>(nameof(FiscalMonth), ref fFiscalMonth, value);
			}
		}
		string fFiscalMonthLabel;
		[Size(20)]
		public string FiscalMonthLabel
		{
			get
			{
				return fFiscalMonthLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(FiscalMonthLabel), ref fFiscalMonthLabel, value);
			}
		}
		string fIsWorkDay;
		[Size(20)]
		public string IsWorkDay
		{
			get
			{
				return fIsWorkDay;
			}
			set
			{
				SetPropertyValue<string>(nameof(IsWorkDay), ref fIsWorkDay, value);
			}
		}
		int fIsHoliday;
		public int IsHoliday
		{
			get
			{
				return fIsHoliday;
			}
			set
			{
				SetPropertyValue<int>(nameof(IsHoliday), ref fIsHoliday, value);
			}
		}
		string fHolidayName;
		[Size(20)]
		public string HolidayName
		{
			get
			{
				return fHolidayName;
			}
			set
			{
				SetPropertyValue<string>(nameof(HolidayName), ref fHolidayName, value);
			}
		}
		string fEuropeSeason;
		[Size(50)]
		public string EuropeSeason
		{
			get
			{
				return fEuropeSeason;
			}
			set
			{
				SetPropertyValue<string>(nameof(EuropeSeason), ref fEuropeSeason, value);
			}
		}
		string fNorthAmericaSeason;
		[Size(50)]
		public string NorthAmericaSeason
		{
			get
			{
				return fNorthAmericaSeason;
			}
			set
			{
				SetPropertyValue<string>(nameof(NorthAmericaSeason), ref fNorthAmericaSeason, value);
			}
		}
		string fAsiaSeason;
		[Size(50)]
		public string AsiaSeason
		{
			get
			{
				return fAsiaSeason;
			}
			set
			{
				SetPropertyValue<string>(nameof(AsiaSeason), ref fAsiaSeason, value);
			}
		}
		[Association(@"FactExchangeRateReferencesDate")]
		public XPCollection<FactExchangeRate> FactExchangeRates
		{
			get
			{
				return GetCollection<FactExchangeRate>(nameof(FactExchangeRates));
			}
		}
		[Association(@"FactInventoryReferencesDate")]
		public XPCollection<FactInventory> FactInventories
		{
			get
			{
				return GetCollection<FactInventory>(nameof(FactInventories));
			}
		}
		[Association(@"FactITMachineReferencesDate")]
		public XPCollection<FactITMachine> FactITMachines
		{
			get
			{
				return GetCollection<FactITMachine>(nameof(FactITMachines));
			}
		}
		[Association(@"FactITSLAReferencesDate")]
		public XPCollection<FactITSLA> FactITSLAs
		{
			get
			{
				return GetCollection<FactITSLA>(nameof(FactITSLAs));
			}
		}
		[Association(@"FactOnlineSalesReferencesDate")]
		public XPCollection<FactOnlineSales> FactOnlineSalesCollection
		{
			get
			{
				return GetCollection<FactOnlineSales>(nameof(FactOnlineSalesCollection));
			}
		}
		[Association(@"FactSalesReferencesDate")]
		public XPCollection<Sales> FactSalesCollection
		{
			get
			{
				return GetCollection<Sales>(nameof(FactSalesCollection));
			}
		}
		[Association(@"FactSalesQuotaReferencesDate")]
		public XPCollection<FactSalesQuota> FactSalesQuotas
		{
			get
			{
				return GetCollection<FactSalesQuota>(nameof(FactSalesQuotas));
			}
		}
		[Association(@"FactStrategyPlanReferencesDate")]
		public XPCollection<FactStrategyPlan> FactStrategyPlans
		{
			get
			{
				return GetCollection<FactStrategyPlan>(nameof(FactStrategyPlans));
			}
		}
	}

}
