//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimEmployee")]
	public partial class Employee : XPLiteObject
	{
		int fEmployeeKey;
		[Key(true)]
		public int EmployeeKey
		{
			get
			{
				return fEmployeeKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(EmployeeKey), ref fEmployeeKey, value);
			}
		}
		Employee fParentEmployeeKey;
		[Association(@"EmployeeReferencesEmployee")]
		public Employee ParentEmployeeKey
		{
			get
			{
				return fParentEmployeeKey;
			}
			set
			{
				SetPropertyValue<Employee>(nameof(ParentEmployeeKey), ref fParentEmployeeKey, value);
			}
		}
		string fFirstName;
		[Size(50)]
		public string FirstName
		{
			get
			{
				return fFirstName;
			}
			set
			{
				SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value);
			}
		}
		string fLastName;
		[Size(50)]
		public string LastName
		{
			get
			{
				return fLastName;
			}
			set
			{
				SetPropertyValue<string>(nameof(LastName), ref fLastName, value);
			}
		}
		string fMiddleName;
		[Size(50)]
		public string MiddleName
		{
			get
			{
				return fMiddleName;
			}
			set
			{
				SetPropertyValue<string>(nameof(MiddleName), ref fMiddleName, value);
			}
		}
		string fTitle;
		[Size(50)]
		public string Title
		{
			get
			{
				return fTitle;
			}
			set
			{
				SetPropertyValue<string>(nameof(Title), ref fTitle, value);
			}
		}
		DateTime fHireDate;
		public DateTime HireDate
		{
			get
			{
				return fHireDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(HireDate), ref fHireDate, value);
			}
		}
		DateTime fBirthDate;
		public DateTime BirthDate
		{
			get
			{
				return fBirthDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(BirthDate), ref fBirthDate, value);
			}
		}
		string fEmailAddress;
		[Size(50)]
		public string EmailAddress
		{
			get
			{
				return fEmailAddress;
			}
			set
			{
				SetPropertyValue<string>(nameof(EmailAddress), ref fEmailAddress, value);
			}
		}
		string fPhone;
		[Size(25)]
		public string Phone
		{
			get
			{
				return fPhone;
			}
			set
			{
				SetPropertyValue<string>(nameof(Phone), ref fPhone, value);
			}
		}
		char fMaritalStatus;
		public char MaritalStatus
		{
			get
			{
				return fMaritalStatus;
			}
			set
			{
				SetPropertyValue<char>(nameof(MaritalStatus), ref fMaritalStatus, value);
			}
		}
		string fEmergencyContactName;
		[Size(50)]
		public string EmergencyContactName
		{
			get
			{
				return fEmergencyContactName;
			}
			set
			{
				SetPropertyValue<string>(nameof(EmergencyContactName), ref fEmergencyContactName, value);
			}
		}
		string fEmergencyContactPhone;
		[Size(25)]
		public string EmergencyContactPhone
		{
			get
			{
				return fEmergencyContactPhone;
			}
			set
			{
				SetPropertyValue<string>(nameof(EmergencyContactPhone), ref fEmergencyContactPhone, value);
			}
		}
		bool fSalariedFlag;
		public bool SalariedFlag
		{
			get
			{
				return fSalariedFlag;
			}
			set
			{
				SetPropertyValue<bool>(nameof(SalariedFlag), ref fSalariedFlag, value);
			}
		}
		char fGender;
		public char Gender
		{
			get
			{
				return fGender;
			}
			set
			{
				SetPropertyValue<char>(nameof(Gender), ref fGender, value);
			}
		}
		byte fPayFrequency;
		public byte PayFrequency
		{
			get
			{
				return fPayFrequency;
			}
			set
			{
				SetPropertyValue<byte>(nameof(PayFrequency), ref fPayFrequency, value);
			}
		}
		decimal fBaseRate;
		public decimal BaseRate
		{
			get
			{
				return fBaseRate;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(BaseRate), ref fBaseRate, value);
			}
		}
		short fVacationHours;
		public short VacationHours
		{
			get
			{
				return fVacationHours;
			}
			set
			{
				SetPropertyValue<short>(nameof(VacationHours), ref fVacationHours, value);
			}
		}
		bool fCurrentFlag;
		public bool CurrentFlag
		{
			get
			{
				return fCurrentFlag;
			}
			set
			{
				SetPropertyValue<bool>(nameof(CurrentFlag), ref fCurrentFlag, value);
			}
		}
		bool fSalesPersonFlag;
		public bool SalesPersonFlag
		{
			get
			{
				return fSalesPersonFlag;
			}
			set
			{
				SetPropertyValue<bool>(nameof(SalesPersonFlag), ref fSalesPersonFlag, value);
			}
		}
		string fDepartmentName;
		[Size(50)]
		public string DepartmentName
		{
			get
			{
				return fDepartmentName;
			}
			set
			{
				SetPropertyValue<string>(nameof(DepartmentName), ref fDepartmentName, value);
			}
		}
		DateTime fStartDate;
		public DateTime StartDate
		{
			get
			{
				return fStartDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(StartDate), ref fStartDate, value);
			}
		}
		DateTime fEndDate;
		public DateTime EndDate
		{
			get
			{
				return fEndDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(EndDate), ref fEndDate, value);
			}
		}
		string fStatus;
		[Size(50)]
		public string Status
		{
			get
			{
				return fStatus;
			}
			set
			{
				SetPropertyValue<string>(nameof(Status), ref fStatus, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
		[Association(@"EmployeeReferencesEmployee")]
		public XPCollection<Employee> EmployeeCollection
		{
			get
			{
				return GetCollection<Employee>(nameof(EmployeeCollection));
			}
		}
	}

}
