//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"FactSalesQuota")]
	public partial class SalesQuota : XPLiteObject
	{
		int fSalesQuotaKey;
		[Key(true)]
		public int SalesQuotaKey
		{
			get
			{
				return fSalesQuotaKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(SalesQuotaKey), ref fSalesQuotaKey, value);
			}
		}
		Channel fChannelKey;
		[Association(@"FactSalesQuotaReferencesChannel")]
		public Channel ChannelKey
		{
			get
			{
				return fChannelKey;
			}
			set
			{
				SetPropertyValue<Channel>(nameof(ChannelKey), ref fChannelKey, value);
			}
		}
		Store fStoreKey;
		[Association(@"FactSalesQuotaReferencesStore")]
		public Store StoreKey
		{
			get
			{
				return fStoreKey;
			}
			set
			{
				SetPropertyValue<Store>(nameof(StoreKey), ref fStoreKey, value);
			}
		}
		Product fProductKey;
		[Association(@"FactSalesQuotaReferencesProduct")]
		public Product ProductKey
		{
			get
			{
				return fProductKey;
			}
			set
			{
				SetPropertyValue<Product>(nameof(ProductKey), ref fProductKey, value);
			}
		}
		Date fDateKey;
		[Association(@"FactSalesQuotaReferencesDate")]
		public Date DateKey
		{
			get
			{
				return fDateKey;
			}
			set
			{
				SetPropertyValue<Date>(nameof(DateKey), ref fDateKey, value);
			}
		}
		Currency fCurrencyKey;
		[Association(@"FactSalesQuotaReferencesCurrency")]
		public Currency CurrencyKey
		{
			get
			{
				return fCurrencyKey;
			}
			set
			{
				SetPropertyValue<Currency>(nameof(CurrencyKey), ref fCurrencyKey, value);
			}
		}
		Scenario fScenarioKey;
		[Association(@"FactSalesQuotaReferencesScenario")]
		public Scenario ScenarioKey
		{
			get
			{
				return fScenarioKey;
			}
			set
			{
				SetPropertyValue<Scenario>(nameof(ScenarioKey), ref fScenarioKey, value);
			}
		}
		decimal fSalesQuantityQuota;
		public decimal SalesQuantityQuota
		{
			get
			{
				return fSalesQuantityQuota;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(SalesQuantityQuota), ref fSalesQuantityQuota, value);
			}
		}
		decimal fSalesAmountQuota;
		public decimal SalesAmountQuota
		{
			get
			{
				return fSalesAmountQuota;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(SalesAmountQuota), ref fSalesAmountQuota, value);
			}
		}
		decimal fGrossMarginQuota;
		public decimal GrossMarginQuota
		{
			get
			{
				return fGrossMarginQuota;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(GrossMarginQuota), ref fGrossMarginQuota, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
	}

}
