//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	public partial class FactITSLA : XPLiteObject
	{
		int fITSLAkey;
		[Key(true)]
		public int ITSLAkey
		{
			get
			{
				return fITSLAkey;
			}
			set
			{
				SetPropertyValue<int>(nameof(ITSLAkey), ref fITSLAkey, value);
			}
		}
		Date fDateKey;
		[Association(@"FactITSLAReferencesDate")]
		public Date DateKey
		{
			get
			{
				return fDateKey;
			}
			set
			{
				SetPropertyValue<Date>(nameof(DateKey), ref fDateKey, value);
			}
		}
		Store fStoreKey;
		[Association(@"FactITSLAReferencesStore")]
		public Store StoreKey
		{
			get
			{
				return fStoreKey;
			}
			set
			{
				SetPropertyValue<Store>(nameof(StoreKey), ref fStoreKey, value);
			}
		}
		Machine fMachineKey;
		[Association(@"FactITSLAReferencesMachine")]
		public Machine MachineKey
		{
			get
			{
				return fMachineKey;
			}
			set
			{
				SetPropertyValue<Machine>(nameof(MachineKey), ref fMachineKey, value);
			}
		}
		Outage fOutageKey;
		[Association(@"FactITSLAReferencesOutage")]
		public Outage OutageKey
		{
			get
			{
				return fOutageKey;
			}
			set
			{
				SetPropertyValue<Outage>(nameof(OutageKey), ref fOutageKey, value);
			}
		}
		DateTime fOutageStartTime;
		public DateTime OutageStartTime
		{
			get
			{
				return fOutageStartTime;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(OutageStartTime), ref fOutageStartTime, value);
			}
		}
		DateTime fOutageEndTime;
		public DateTime OutageEndTime
		{
			get
			{
				return fOutageEndTime;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(OutageEndTime), ref fOutageEndTime, value);
			}
		}
		int fDownTime;
		public int DownTime
		{
			get
			{
				return fDownTime;
			}
			set
			{
				SetPropertyValue<int>(nameof(DownTime), ref fDownTime, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
	}

}
