//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	public partial class FactOnlineSales : XPLiteObject
	{
		int fOnlineSalesKey;
		[Key(true)]
		public int OnlineSalesKey
		{
			get
			{
				return fOnlineSalesKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(OnlineSalesKey), ref fOnlineSalesKey, value);
			}
		}
		Date fDateKey;
		[Association(@"FactOnlineSalesReferencesDate")]
		public Date DateKey
		{
			get
			{
				return fDateKey;
			}
			set
			{
				SetPropertyValue<Date>(nameof(DateKey), ref fDateKey, value);
			}
		}
		Store fStoreKey;
		[Association(@"FactOnlineSalesReferencesStore")]
		public Store StoreKey
		{
			get
			{
				return fStoreKey;
			}
			set
			{
				SetPropertyValue<Store>(nameof(StoreKey), ref fStoreKey, value);
			}
		}
		Product fProductKey;
		[Association(@"FactOnlineSalesReferencesProduct")]
		public Product ProductKey
		{
			get
			{
				return fProductKey;
			}
			set
			{
				SetPropertyValue<Product>(nameof(ProductKey), ref fProductKey, value);
			}
		}
		Promotion fPromotionKey;
		[Association(@"FactOnlineSalesReferencesPromotion")]
		public Promotion PromotionKey
		{
			get
			{
				return fPromotionKey;
			}
			set
			{
				SetPropertyValue<Promotion>(nameof(PromotionKey), ref fPromotionKey, value);
			}
		}
		Currency fCurrencyKey;
		[Association(@"FactOnlineSalesReferencesCurrency")]
		public Currency CurrencyKey
		{
			get
			{
				return fCurrencyKey;
			}
			set
			{
				SetPropertyValue<Currency>(nameof(CurrencyKey), ref fCurrencyKey, value);
			}
		}
		Customer fCustomerKey;
		[Association(@"FactOnlineSalesReferencesCustomer")]
		public Customer CustomerKey
		{
			get
			{
				return fCustomerKey;
			}
			set
			{
				SetPropertyValue<Customer>(nameof(CustomerKey), ref fCustomerKey, value);
			}
		}
		string fSalesOrderNumber;
		[Size(20)]
		public string SalesOrderNumber
		{
			get
			{
				return fSalesOrderNumber;
			}
			set
			{
				SetPropertyValue<string>(nameof(SalesOrderNumber), ref fSalesOrderNumber, value);
			}
		}
		int fSalesOrderLineNumber;
		public int SalesOrderLineNumber
		{
			get
			{
				return fSalesOrderLineNumber;
			}
			set
			{
				SetPropertyValue<int>(nameof(SalesOrderLineNumber), ref fSalesOrderLineNumber, value);
			}
		}
		int fSalesQuantity;
		public int SalesQuantity
		{
			get
			{
				return fSalesQuantity;
			}
			set
			{
				SetPropertyValue<int>(nameof(SalesQuantity), ref fSalesQuantity, value);
			}
		}
		decimal fSalesAmount;
		public decimal SalesAmount
		{
			get
			{
				return fSalesAmount;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(SalesAmount), ref fSalesAmount, value);
			}
		}
		int fReturnQuantity;
		public int ReturnQuantity
		{
			get
			{
				return fReturnQuantity;
			}
			set
			{
				SetPropertyValue<int>(nameof(ReturnQuantity), ref fReturnQuantity, value);
			}
		}
		decimal fReturnAmount;
		public decimal ReturnAmount
		{
			get
			{
				return fReturnAmount;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(ReturnAmount), ref fReturnAmount, value);
			}
		}
		int fDiscountQuantity;
		public int DiscountQuantity
		{
			get
			{
				return fDiscountQuantity;
			}
			set
			{
				SetPropertyValue<int>(nameof(DiscountQuantity), ref fDiscountQuantity, value);
			}
		}
		decimal fDiscountAmount;
		public decimal DiscountAmount
		{
			get
			{
				return fDiscountAmount;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(DiscountAmount), ref fDiscountAmount, value);
			}
		}
		decimal fTotalCost;
		public decimal TotalCost
		{
			get
			{
				return fTotalCost;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(TotalCost), ref fTotalCost, value);
			}
		}
		decimal fUnitCost;
		public decimal UnitCost
		{
			get
			{
				return fUnitCost;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(UnitCost), ref fUnitCost, value);
			}
		}
		decimal fUnitPrice;
		public decimal UnitPrice
		{
			get
			{
				return fUnitPrice;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(UnitPrice), ref fUnitPrice, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
	}

}
