//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"FactExchangeRate")]
	public partial class ExchangeRate : XPLiteObject
	{
		int fExchangeRateKey;
		[Key(true)]
		public int ExchangeRateKey
		{
			get
			{
				return fExchangeRateKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(ExchangeRateKey), ref fExchangeRateKey, value);
			}
		}
		Currency fCurrencyKey;
		[Association(@"FactExchangeRateReferencesCurrency")]
		public Currency CurrencyKey
		{
			get
			{
				return fCurrencyKey;
			}
			set
			{
				SetPropertyValue<Currency>(nameof(CurrencyKey), ref fCurrencyKey, value);
			}
		}
		Date fDateKey;
		[Association(@"FactExchangeRateReferencesDate")]
		public Date DateKey
		{
			get
			{
				return fDateKey;
			}
			set
			{
				SetPropertyValue<Date>(nameof(DateKey), ref fDateKey, value);
			}
		}
		double fAverageRate;
		public double AverageRate
		{
			get
			{
				return fAverageRate;
			}
			set
			{
				SetPropertyValue<double>(nameof(AverageRate), ref fAverageRate, value);
			}
		}
		double fEndOfDayRate;
		public double EndOfDayRate
		{
			get
			{
				return fEndOfDayRate;
			}
			set
			{
				SetPropertyValue<double>(nameof(EndOfDayRate), ref fEndOfDayRate, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
	}

}
