//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"FactITMachine")]
	public partial class ITMachine : XPLiteObject
	{
		int fITMachinekey;
		[Key(true)]
		public int ITMachinekey
		{
			get
			{
				return fITMachinekey;
			}
			set
			{
				SetPropertyValue<int>(nameof(ITMachinekey), ref fITMachinekey, value);
			}
		}
		Machine fMachineKey;
		[Association(@"FactITMachineReferencesMachine")]
		public Machine MachineKey
		{
			get
			{
				return fMachineKey;
			}
			set
			{
				SetPropertyValue<Machine>(nameof(MachineKey), ref fMachineKey, value);
			}
		}
		Date fDatekey;
		[Association(@"FactITMachineReferencesDate")]
		public Date Datekey
		{
			get
			{
				return fDatekey;
			}
			set
			{
				SetPropertyValue<Date>(nameof(Datekey), ref fDatekey, value);
			}
		}
		decimal fCostAmount;
		public decimal CostAmount
		{
			get
			{
				return fCostAmount;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(CostAmount), ref fCostAmount, value);
			}
		}
		string fCostType;
		[Size(200)]
		public string CostType
		{
			get
			{
				return fCostType;
			}
			set
			{
				SetPropertyValue<string>(nameof(CostType), ref fCostType, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
	}

}
