//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"FactInventory")]
	public partial class Inventory : XPLiteObject
	{
		int fInventoryKey;
		[Key(true)]
		public int InventoryKey
		{
			get
			{
				return fInventoryKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(InventoryKey), ref fInventoryKey, value);
			}
		}
		Date fDateKey;
		[Association(@"FactInventoryReferencesDate")]
		public Date DateKey
		{
			get
			{
				return fDateKey;
			}
			set
			{
				SetPropertyValue<Date>(nameof(DateKey), ref fDateKey, value);
			}
		}
		Store fStoreKey;
		[Association(@"FactInventoryReferencesStore")]
		public Store StoreKey
		{
			get
			{
				return fStoreKey;
			}
			set
			{
				SetPropertyValue<Store>(nameof(StoreKey), ref fStoreKey, value);
			}
		}
		Product fProductKey;
		[Association(@"FactInventoryReferencesProduct")]
		public Product ProductKey
		{
			get
			{
				return fProductKey;
			}
			set
			{
				SetPropertyValue<Product>(nameof(ProductKey), ref fProductKey, value);
			}
		}
		Currency fCurrencyKey;
		[Association(@"FactInventoryReferencesCurrency")]
		public Currency CurrencyKey
		{
			get
			{
				return fCurrencyKey;
			}
			set
			{
				SetPropertyValue<Currency>(nameof(CurrencyKey), ref fCurrencyKey, value);
			}
		}
		int fOnHandQuantity;
		public int OnHandQuantity
		{
			get
			{
				return fOnHandQuantity;
			}
			set
			{
				SetPropertyValue<int>(nameof(OnHandQuantity), ref fOnHandQuantity, value);
			}
		}
		int fOnOrderQuantity;
		public int OnOrderQuantity
		{
			get
			{
				return fOnOrderQuantity;
			}
			set
			{
				SetPropertyValue<int>(nameof(OnOrderQuantity), ref fOnOrderQuantity, value);
			}
		}
		int fSafetyStockQuantity;
		public int SafetyStockQuantity
		{
			get
			{
				return fSafetyStockQuantity;
			}
			set
			{
				SetPropertyValue<int>(nameof(SafetyStockQuantity), ref fSafetyStockQuantity, value);
			}
		}
		decimal fUnitCost;
		public decimal UnitCost
		{
			get
			{
				return fUnitCost;
			}
			set
			{
				SetPropertyValue<decimal>(nameof(UnitCost), ref fUnitCost, value);
			}
		}
		int fDaysInStock;
		public int DaysInStock
		{
			get
			{
				return fDaysInStock;
			}
			set
			{
				SetPropertyValue<int>(nameof(DaysInStock), ref fDaysInStock, value);
			}
		}
		int fMinDayInStock;
		public int MinDayInStock
		{
			get
			{
				return fMinDayInStock;
			}
			set
			{
				SetPropertyValue<int>(nameof(MinDayInStock), ref fMinDayInStock, value);
			}
		}
		int fMaxDayInStock;
		public int MaxDayInStock
		{
			get
			{
				return fMaxDayInStock;
			}
			set
			{
				SetPropertyValue<int>(nameof(MaxDayInStock), ref fMaxDayInStock, value);
			}
		}
		int fAging;
		public int Aging
		{
			get
			{
				return fAging;
			}
			set
			{
				SetPropertyValue<int>(nameof(Aging), ref fAging, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
	}

}
