//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimGeography")]
	public partial class Geography : XPLiteObject
	{
		int fGeographyKey;
		[Key(true)]
		public int GeographyKey
		{
			get
			{
				return fGeographyKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(GeographyKey), ref fGeographyKey, value);
			}
		}
		string fGeographyType;
		[Size(50)]
		public string GeographyType
		{
			get
			{
				return fGeographyType;
			}
			set
			{
				SetPropertyValue<string>(nameof(GeographyType), ref fGeographyType, value);
			}
		}
		string fContinentName;
		[Size(50)]
		public string ContinentName
		{
			get
			{
				return fContinentName;
			}
			set
			{
				SetPropertyValue<string>(nameof(ContinentName), ref fContinentName, value);
			}
		}
		string fCityName;
		public string CityName
		{
			get
			{
				return fCityName;
			}
			set
			{
				SetPropertyValue<string>(nameof(CityName), ref fCityName, value);
			}
		}
		string fStateProvinceName;
		public string StateProvinceName
		{
			get
			{
				return fStateProvinceName;
			}
			set
			{
				SetPropertyValue<string>(nameof(StateProvinceName), ref fStateProvinceName, value);
			}
		}
		string fRegionCountryName;
		public string RegionCountryName
		{
			get
			{
				return fRegionCountryName;
			}
			set
			{
				SetPropertyValue<string>(nameof(RegionCountryName), ref fRegionCountryName, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
		[Association(@"CustomerReferencesGeography")]
		public XPCollection<Customer> Customers
		{
			get
			{
				return GetCollection<Customer>(nameof(Customers));
			}
		}
		[Association(@"SalesTerritoryReferencesGeography")]
		public XPCollection<SalesTerritory> SalesTerritories
		{
			get
			{
				return GetCollection<SalesTerritory>(nameof(SalesTerritories));
			}
		}
		[Association(@"StoreReferencesGeography")]
		public XPCollection<Store> Stores
		{
			get
			{
				return GetCollection<Store>(nameof(Stores));
			}
		}
	}

}
