//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimMachine")]
	public partial class Machine : XPLiteObject
	{
		int fMachineKey;
		[Key]
		public int MachineKey
		{
			get
			{
				return fMachineKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(MachineKey), ref fMachineKey, value);
			}
		}
		string fMachineLabel;
		public string MachineLabel
		{
			get
			{
				return fMachineLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(MachineLabel), ref fMachineLabel, value);
			}
		}
		Store fStoreKey;
		[Association(@"MachineReferencesStore")]
		public Store StoreKey
		{
			get
			{
				return fStoreKey;
			}
			set
			{
				SetPropertyValue<Store>(nameof(StoreKey), ref fStoreKey, value);
			}
		}
		string fMachineType;
		[Size(50)]
		public string MachineType
		{
			get
			{
				return fMachineType;
			}
			set
			{
				SetPropertyValue<string>(nameof(MachineType), ref fMachineType, value);
			}
		}
		string fMachineName;
		public string MachineName
		{
			get
			{
				return fMachineName;
			}
			set
			{
				SetPropertyValue<string>(nameof(MachineName), ref fMachineName, value);
			}
		}
		string fMachineDescription;
		[Size(200)]
		public string MachineDescription
		{
			get
			{
				return fMachineDescription;
			}
			set
			{
				SetPropertyValue<string>(nameof(MachineDescription), ref fMachineDescription, value);
			}
		}
		string fVendorName;
		[Size(50)]
		public string VendorName
		{
			get
			{
				return fVendorName;
			}
			set
			{
				SetPropertyValue<string>(nameof(VendorName), ref fVendorName, value);
			}
		}
		string fMachineOS;
		[Size(50)]
		public string MachineOS
		{
			get
			{
				return fMachineOS;
			}
			set
			{
				SetPropertyValue<string>(nameof(MachineOS), ref fMachineOS, value);
			}
		}
		string fMachineSource;
		public string MachineSource
		{
			get
			{
				return fMachineSource;
			}
			set
			{
				SetPropertyValue<string>(nameof(MachineSource), ref fMachineSource, value);
			}
		}
		string fMachineHardware;
		public string MachineHardware
		{
			get
			{
				return fMachineHardware;
			}
			set
			{
				SetPropertyValue<string>(nameof(MachineHardware), ref fMachineHardware, value);
			}
		}
		string fMachineSoftware;
		public string MachineSoftware
		{
			get
			{
				return fMachineSoftware;
			}
			set
			{
				SetPropertyValue<string>(nameof(MachineSoftware), ref fMachineSoftware, value);
			}
		}
		string fStatus;
		[Size(50)]
		public string Status
		{
			get
			{
				return fStatus;
			}
			set
			{
				SetPropertyValue<string>(nameof(Status), ref fStatus, value);
			}
		}
		DateTime fServiceStartDate;
		public DateTime ServiceStartDate
		{
			get
			{
				return fServiceStartDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(ServiceStartDate), ref fServiceStartDate, value);
			}
		}
		DateTime fDecommissionDate;
		public DateTime DecommissionDate
		{
			get
			{
				return fDecommissionDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(DecommissionDate), ref fDecommissionDate, value);
			}
		}
		DateTime fLastModifiedDate;
		public DateTime LastModifiedDate
		{
			get
			{
				return fLastModifiedDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LastModifiedDate), ref fLastModifiedDate, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
		[Association(@"FactITMachineReferencesMachine")]
		public XPCollection<FactITMachine> FactITMachines
		{
			get
			{
				return GetCollection<FactITMachine>(nameof(FactITMachines));
			}
		}
		[Association(@"FactITSLAReferencesMachine")]
		public XPCollection<FactITSLA> FactITSLAs
		{
			get
			{
				return GetCollection<FactITSLA>(nameof(FactITSLAs));
			}
		}
	}

}
