//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimOutage")]
	public partial class Outage : XPLiteObject
	{
		int fOutageKey;
		[Key(true)]
		public int OutageKey
		{
			get
			{
				return fOutageKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(OutageKey), ref fOutageKey, value);
			}
		}
		string fOutageLabel;
		public string OutageLabel
		{
			get
			{
				return fOutageLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(OutageLabel), ref fOutageLabel, value);
			}
		}
		string fOutageName;
		[Size(50)]
		public string OutageName
		{
			get
			{
				return fOutageName;
			}
			set
			{
				SetPropertyValue<string>(nameof(OutageName), ref fOutageName, value);
			}
		}
		string fOutageDescription;
		[Size(200)]
		public string OutageDescription
		{
			get
			{
				return fOutageDescription;
			}
			set
			{
				SetPropertyValue<string>(nameof(OutageDescription), ref fOutageDescription, value);
			}
		}
		string fOutageType;
		[Size(50)]
		public string OutageType
		{
			get
			{
				return fOutageType;
			}
			set
			{
				SetPropertyValue<string>(nameof(OutageType), ref fOutageType, value);
			}
		}
		string fOutageTypeDescription;
		[Size(200)]
		public string OutageTypeDescription
		{
			get
			{
				return fOutageTypeDescription;
			}
			set
			{
				SetPropertyValue<string>(nameof(OutageTypeDescription), ref fOutageTypeDescription, value);
			}
		}
		string fOutageSubType;
		[Size(50)]
		public string OutageSubType
		{
			get
			{
				return fOutageSubType;
			}
			set
			{
				SetPropertyValue<string>(nameof(OutageSubType), ref fOutageSubType, value);
			}
		}
		string fOutageSubTypeDescription;
		[Size(200)]
		public string OutageSubTypeDescription
		{
			get
			{
				return fOutageSubTypeDescription;
			}
			set
			{
				SetPropertyValue<string>(nameof(OutageSubTypeDescription), ref fOutageSubTypeDescription, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
		[Association(@"FactITSLAReferencesOutage")]
		public XPCollection<ITSLA> FactITSLAs
		{
			get
			{
				return GetCollection<ITSLA>(nameof(FactITSLAs));
			}
		}
	}

}
