//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimProductSubcategory")]
	public partial class ProductSubcategory : XPLiteObject
	{
		int fProductSubcategoryKey;
		[Key(true)]
		public int ProductSubcategoryKey
		{
			get
			{
				return fProductSubcategoryKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(ProductSubcategoryKey), ref fProductSubcategoryKey, value);
			}
		}
		string fProductSubcategoryLabel;
		[Indexed(Name = @"AK_DimProductSubcategory_ProductSubcategoryLabel", Unique = true)]
		public string ProductSubcategoryLabel
		{
			get
			{
				return fProductSubcategoryLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(ProductSubcategoryLabel), ref fProductSubcategoryLabel, value);
			}
		}
		string fProductSubcategoryName;
		[Size(50)]
		public string ProductSubcategoryName
		{
			get
			{
				return fProductSubcategoryName;
			}
			set
			{
				SetPropertyValue<string>(nameof(ProductSubcategoryName), ref fProductSubcategoryName, value);
			}
		}
		string fProductSubcategoryDescription;
		public string ProductSubcategoryDescription
		{
			get
			{
				return fProductSubcategoryDescription;
			}
			set
			{
				SetPropertyValue<string>(nameof(ProductSubcategoryDescription), ref fProductSubcategoryDescription, value);
			}
		}
		ProductCategory fProductCategoryKey;
		[Association(@"ProductSubcategoryReferencesProductCategory")]
		public ProductCategory ProductCategoryKey
		{
			get
			{
				return fProductCategoryKey;
			}
			set
			{
				SetPropertyValue<ProductCategory>(nameof(ProductCategoryKey), ref fProductCategoryKey, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
		[Association(@"ProductReferencesProductSubcategory")]
		public XPCollection<Product> Products
		{
			get
			{
				return GetCollection<Product>(nameof(Products));
			}
		}
	}

}
