//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimProductCategory")]
	public partial class ProductCategory : XPLiteObject
	{
		int fProductCategoryKey;
		[Key(true)]
		public int ProductCategoryKey
		{
			get
			{
				return fProductCategoryKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(ProductCategoryKey), ref fProductCategoryKey, value);
			}
		}
		string fProductCategoryLabel;
		[Indexed(Name = @"AK_DimProductCategory_ProductCategoryLabel", Unique = true)]
		public string ProductCategoryLabel
		{
			get
			{
				return fProductCategoryLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(ProductCategoryLabel), ref fProductCategoryLabel, value);
			}
		}
		string fProductCategoryName;
		[Size(30)]
		public string ProductCategoryName
		{
			get
			{
				return fProductCategoryName;
			}
			set
			{
				SetPropertyValue<string>(nameof(ProductCategoryName), ref fProductCategoryName, value);
			}
		}
		string fProductCategoryDescription;
		[Size(50)]
		public string ProductCategoryDescription
		{
			get
			{
				return fProductCategoryDescription;
			}
			set
			{
				SetPropertyValue<string>(nameof(ProductCategoryDescription), ref fProductCategoryDescription, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
		[Association(@"ProductSubcategoryReferencesProductCategory")]
		public XPCollection<ProductSubcategory> ProductSubcategories
		{
			get
			{
				return GetCollection<ProductSubcategory>(nameof(ProductSubcategories));
			}
		}
		[Association(@"FactStrategyPlanReferencesProductCategory")]
		public XPCollection<StrategyPlan> FactStrategyPlans
		{
			get
			{
				return GetCollection<StrategyPlan>(nameof(FactStrategyPlans));
			}
		}
	}

}
