//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimPromotion")]
	public partial class Promotion : XPLiteObject
	{
		int fPromotionKey;
		[Key(true)]
		public int PromotionKey
		{
			get
			{
				return fPromotionKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(PromotionKey), ref fPromotionKey, value);
			}
		}
		string fPromotionLabel;
		[Indexed(Name = @"AK_DimPromotion_PromotionLabel", Unique = true)]
		public string PromotionLabel
		{
			get
			{
				return fPromotionLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(PromotionLabel), ref fPromotionLabel, value);
			}
		}
		string fPromotionName;
		public string PromotionName
		{
			get
			{
				return fPromotionName;
			}
			set
			{
				SetPropertyValue<string>(nameof(PromotionName), ref fPromotionName, value);
			}
		}
		string fPromotionDescription;
		[Size(255)]
		public string PromotionDescription
		{
			get
			{
				return fPromotionDescription;
			}
			set
			{
				SetPropertyValue<string>(nameof(PromotionDescription), ref fPromotionDescription, value);
			}
		}
		double fDiscountPercent;
		public double DiscountPercent
		{
			get
			{
				return fDiscountPercent;
			}
			set
			{
				SetPropertyValue<double>(nameof(DiscountPercent), ref fDiscountPercent, value);
			}
		}
		string fPromotionType;
		[Size(50)]
		public string PromotionType
		{
			get
			{
				return fPromotionType;
			}
			set
			{
				SetPropertyValue<string>(nameof(PromotionType), ref fPromotionType, value);
			}
		}
		string fPromotionCategory;
		[Size(50)]
		public string PromotionCategory
		{
			get
			{
				return fPromotionCategory;
			}
			set
			{
				SetPropertyValue<string>(nameof(PromotionCategory), ref fPromotionCategory, value);
			}
		}
		DateTime fStartDate;
		public DateTime StartDate
		{
			get
			{
				return fStartDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(StartDate), ref fStartDate, value);
			}
		}
		DateTime fEndDate;
		public DateTime EndDate
		{
			get
			{
				return fEndDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(EndDate), ref fEndDate, value);
			}
		}
		int fMinQuantity;
		public int MinQuantity
		{
			get
			{
				return fMinQuantity;
			}
			set
			{
				SetPropertyValue<int>(nameof(MinQuantity), ref fMinQuantity, value);
			}
		}
		int fMaxQuantity;
		public int MaxQuantity
		{
			get
			{
				return fMaxQuantity;
			}
			set
			{
				SetPropertyValue<int>(nameof(MaxQuantity), ref fMaxQuantity, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
		[Association(@"FactOnlineSalesReferencesPromotion")]
		public XPCollection<FactOnlineSales> FactOnlineSalesCollection
		{
			get
			{
				return GetCollection<FactOnlineSales>(nameof(FactOnlineSalesCollection));
			}
		}
		[Association(@"FactSalesReferencesPromotion")]
		public XPCollection<Sales> FactSalesCollection
		{
			get
			{
				return GetCollection<Sales>(nameof(FactSalesCollection));
			}
		}
	}

}
