//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimSalesTerritory")]
	public partial class SalesTerritory : XPLiteObject
	{
		int fSalesTerritoryKey;
		[Key(true)]
		public int SalesTerritoryKey
		{
			get
			{
				return fSalesTerritoryKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(SalesTerritoryKey), ref fSalesTerritoryKey, value);
			}
		}
		Geography fGeographyKey;
		[Association(@"SalesTerritoryReferencesGeography")]
		public Geography GeographyKey
		{
			get
			{
				return fGeographyKey;
			}
			set
			{
				SetPropertyValue<Geography>(nameof(GeographyKey), ref fGeographyKey, value);
			}
		}
		string fSalesTerritoryLabel;
		[Indexed(Name = @"AK_DimSalesTerritory_SalesTerritoryLabel", Unique = true)]
		public string SalesTerritoryLabel
		{
			get
			{
				return fSalesTerritoryLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(SalesTerritoryLabel), ref fSalesTerritoryLabel, value);
			}
		}
		string fSalesTerritoryName;
		[Size(50)]
		public string SalesTerritoryName
		{
			get
			{
				return fSalesTerritoryName;
			}
			set
			{
				SetPropertyValue<string>(nameof(SalesTerritoryName), ref fSalesTerritoryName, value);
			}
		}
		string fSalesTerritoryRegion;
		[Size(50)]
		public string SalesTerritoryRegion
		{
			get
			{
				return fSalesTerritoryRegion;
			}
			set
			{
				SetPropertyValue<string>(nameof(SalesTerritoryRegion), ref fSalesTerritoryRegion, value);
			}
		}
		string fSalesTerritoryCountry;
		[Size(50)]
		public string SalesTerritoryCountry
		{
			get
			{
				return fSalesTerritoryCountry;
			}
			set
			{
				SetPropertyValue<string>(nameof(SalesTerritoryCountry), ref fSalesTerritoryCountry, value);
			}
		}
		string fSalesTerritoryGroup;
		[Size(50)]
		public string SalesTerritoryGroup
		{
			get
			{
				return fSalesTerritoryGroup;
			}
			set
			{
				SetPropertyValue<string>(nameof(SalesTerritoryGroup), ref fSalesTerritoryGroup, value);
			}
		}
		string fSalesTerritoryLevel;
		[Size(10)]
		public string SalesTerritoryLevel
		{
			get
			{
				return fSalesTerritoryLevel;
			}
			set
			{
				SetPropertyValue<string>(nameof(SalesTerritoryLevel), ref fSalesTerritoryLevel, value);
			}
		}
		int fSalesTerritoryManager;
		public int SalesTerritoryManager
		{
			get
			{
				return fSalesTerritoryManager;
			}
			set
			{
				SetPropertyValue<int>(nameof(SalesTerritoryManager), ref fSalesTerritoryManager, value);
			}
		}
		DateTime fStartDate;
		public DateTime StartDate
		{
			get
			{
				return fStartDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(StartDate), ref fStartDate, value);
			}
		}
		DateTime fEndDate;
		public DateTime EndDate
		{
			get
			{
				return fEndDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(EndDate), ref fEndDate, value);
			}
		}
		string fStatus;
		[Size(50)]
		public string Status
		{
			get
			{
				return fStatus;
			}
			set
			{
				SetPropertyValue<string>(nameof(Status), ref fStatus, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
	}

}
