//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimScenario")]
	public partial class Scenario : XPLiteObject
	{
		int fScenarioKey;
		[Key(true)]
		public int ScenarioKey
		{
			get
			{
				return fScenarioKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(ScenarioKey), ref fScenarioKey, value);
			}
		}
		string fScenarioLabel;
		public string ScenarioLabel
		{
			get
			{
				return fScenarioLabel;
			}
			set
			{
				SetPropertyValue<string>(nameof(ScenarioLabel), ref fScenarioLabel, value);
			}
		}
		string fScenarioName;
		[Size(20)]
		public string ScenarioName
		{
			get
			{
				return fScenarioName;
			}
			set
			{
				SetPropertyValue<string>(nameof(ScenarioName), ref fScenarioName, value);
			}
		}
		string fScenarioDescription;
		[Size(50)]
		public string ScenarioDescription
		{
			get
			{
				return fScenarioDescription;
			}
			set
			{
				SetPropertyValue<string>(nameof(ScenarioDescription), ref fScenarioDescription, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
		[Association(@"FactSalesQuotaReferencesScenario")]
		public XPCollection<SalesQuota> FactSalesQuotas
		{
			get
			{
				return GetCollection<SalesQuota>(nameof(FactSalesQuotas));
			}
		}
		[Association(@"FactStrategyPlanReferencesScenario")]
		public XPCollection<StrategyPlan> FactStrategyPlans
		{
			get
			{
				return GetCollection<StrategyPlan>(nameof(FactStrategyPlans));
			}
		}
	}

}
