//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	[Persistent(@"DimStore")]
	public partial class Store : XPLiteObject
	{
		int fStoreKey;
		[Key(true)]
		public int StoreKey
		{
			get
			{
				return fStoreKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(StoreKey), ref fStoreKey, value);
			}
		}
		Geography fGeographyKey;
		[Association(@"StoreReferencesGeography")]
		public Geography GeographyKey
		{
			get
			{
				return fGeographyKey;
			}
			set
			{
				SetPropertyValue<Geography>(nameof(GeographyKey), ref fGeographyKey, value);
			}
		}
		int fStoreManager;
		public int StoreManager
		{
			get
			{
				return fStoreManager;
			}
			set
			{
				SetPropertyValue<int>(nameof(StoreManager), ref fStoreManager, value);
			}
		}
		string fStoreType;
		[Size(15)]
		public string StoreType
		{
			get
			{
				return fStoreType;
			}
			set
			{
				SetPropertyValue<string>(nameof(StoreType), ref fStoreType, value);
			}
		}
		string fStoreName;
		public string StoreName
		{
			get
			{
				return fStoreName;
			}
			set
			{
				SetPropertyValue<string>(nameof(StoreName), ref fStoreName, value);
			}
		}
		string fStoreDescription;
		[Size(300)]
		public string StoreDescription
		{
			get
			{
				return fStoreDescription;
			}
			set
			{
				SetPropertyValue<string>(nameof(StoreDescription), ref fStoreDescription, value);
			}
		}
		string fStatus;
		[Size(20)]
		public string Status
		{
			get
			{
				return fStatus;
			}
			set
			{
				SetPropertyValue<string>(nameof(Status), ref fStatus, value);
			}
		}
		DateTime fOpenDate;
		public DateTime OpenDate
		{
			get
			{
				return fOpenDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(OpenDate), ref fOpenDate, value);
			}
		}
		DateTime fCloseDate;
		public DateTime CloseDate
		{
			get
			{
				return fCloseDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(CloseDate), ref fCloseDate, value);
			}
		}
		int fEntityKey;
		public int EntityKey
		{
			get
			{
				return fEntityKey;
			}
			set
			{
				SetPropertyValue<int>(nameof(EntityKey), ref fEntityKey, value);
			}
		}
		string fZipCode;
		[Size(20)]
		public string ZipCode
		{
			get
			{
				return fZipCode;
			}
			set
			{
				SetPropertyValue<string>(nameof(ZipCode), ref fZipCode, value);
			}
		}
		string fZipCodeExtension;
		[Size(10)]
		public string ZipCodeExtension
		{
			get
			{
				return fZipCodeExtension;
			}
			set
			{
				SetPropertyValue<string>(nameof(ZipCodeExtension), ref fZipCodeExtension, value);
			}
		}
		string fStorePhone;
		[Size(15)]
		public string StorePhone
		{
			get
			{
				return fStorePhone;
			}
			set
			{
				SetPropertyValue<string>(nameof(StorePhone), ref fStorePhone, value);
			}
		}
		string fStoreFax;
		[Size(14)]
		public string StoreFax
		{
			get
			{
				return fStoreFax;
			}
			set
			{
				SetPropertyValue<string>(nameof(StoreFax), ref fStoreFax, value);
			}
		}
		string fAddressLine1;
		public string AddressLine1
		{
			get
			{
				return fAddressLine1;
			}
			set
			{
				SetPropertyValue<string>(nameof(AddressLine1), ref fAddressLine1, value);
			}
		}
		string fAddressLine2;
		public string AddressLine2
		{
			get
			{
				return fAddressLine2;
			}
			set
			{
				SetPropertyValue<string>(nameof(AddressLine2), ref fAddressLine2, value);
			}
		}
		string fCloseReason;
		[Size(20)]
		public string CloseReason
		{
			get
			{
				return fCloseReason;
			}
			set
			{
				SetPropertyValue<string>(nameof(CloseReason), ref fCloseReason, value);
			}
		}
		int fEmployeeCount;
		public int EmployeeCount
		{
			get
			{
				return fEmployeeCount;
			}
			set
			{
				SetPropertyValue<int>(nameof(EmployeeCount), ref fEmployeeCount, value);
			}
		}
		double fSellingAreaSize;
		public double SellingAreaSize
		{
			get
			{
				return fSellingAreaSize;
			}
			set
			{
				SetPropertyValue<double>(nameof(SellingAreaSize), ref fSellingAreaSize, value);
			}
		}
		DateTime fLastRemodelDate;
		public DateTime LastRemodelDate
		{
			get
			{
				return fLastRemodelDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LastRemodelDate), ref fLastRemodelDate, value);
			}
		}
		int fETLLoadID;
		public int ETLLoadID
		{
			get
			{
				return fETLLoadID;
			}
			set
			{
				SetPropertyValue<int>(nameof(ETLLoadID), ref fETLLoadID, value);
			}
		}
		DateTime fLoadDate;
		public DateTime LoadDate
		{
			get
			{
				return fLoadDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value);
			}
		}
		DateTime fUpdateDate;
		public DateTime UpdateDate
		{
			get
			{
				return fUpdateDate;
			}
			set
			{
				SetPropertyValue<DateTime>(nameof(UpdateDate), ref fUpdateDate, value);
			}
		}
		[Association(@"MachineReferencesStore")]
		public XPCollection<Machine> Machines
		{
			get
			{
				return GetCollection<Machine>(nameof(Machines));
			}
		}
		[Association(@"FactInventoryReferencesStore")]
		public XPCollection<FactInventory> FactInventories
		{
			get
			{
				return GetCollection<FactInventory>(nameof(FactInventories));
			}
		}
		[Association(@"FactITSLAReferencesStore")]
		public XPCollection<FactITSLA> FactITSLAs
		{
			get
			{
				return GetCollection<FactITSLA>(nameof(FactITSLAs));
			}
		}
		[Association(@"FactOnlineSalesReferencesStore")]
		public XPCollection<FactOnlineSales> FactOnlineSalesCollection
		{
			get
			{
				return GetCollection<FactOnlineSales>(nameof(FactOnlineSalesCollection));
			}
		}
		[Association(@"FactSalesReferencesStore")]
		public XPCollection<Sales> FactSalesCollection
		{
			get
			{
				return GetCollection<Sales>(nameof(FactSalesCollection));
			}
		}
		[Association(@"FactSalesQuotaReferencesStore")]
		public XPCollection<FactSalesQuota> FactSalesQuotas
		{
			get
			{
				return GetCollection<FactSalesQuota>(nameof(FactSalesQuotas));
			}
		}
	}

}
