//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SenDev.DashboardsDemo.Module.BusinessObjects
{

	public partial class sysdiagrams : XPLiteObject
	{
		string fname;
		[Size(128)]
		public string name
		{
			get
			{
				return fname;
			}
			set
			{
				SetPropertyValue<string>(nameof(name), ref fname, value);
			}
		}
		int fprincipal_id;
		[Indexed(@"name", Name = @"UK_principal_name", Unique = true)]
		public int principal_id
		{
			get
			{
				return fprincipal_id;
			}
			set
			{
				SetPropertyValue<int>(nameof(principal_id), ref fprincipal_id, value);
			}
		}
		int fdiagram_id;
		[Key(true)]
		public int diagram_id
		{
			get
			{
				return fdiagram_id;
			}
			set
			{
				SetPropertyValue<int>(nameof(diagram_id), ref fdiagram_id, value);
			}
		}
		int fversion;
		public int version
		{
			get
			{
				return fversion;
			}
			set
			{
				SetPropertyValue<int>(nameof(version), ref fversion, value);
			}
		}
		byte[] fdefinition;
		[Size(SizeAttribute.Unlimited)]
		[MemberDesignTimeVisibility(true)]
		public byte[] definition
		{
			get
			{
				return fdefinition;
			}
			set
			{
				SetPropertyValue<byte[]>(nameof(definition), ref fdefinition, value);
			}
		}
	}

}
